[tool.poetry]
name = "til"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sagemaker = "^2.231.0"
locust = "^2.31.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
